project_id = "oxybjnljvzhbvnirhlkv"

[functions.generate-carousel]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.greenn-webhook]
verify_jwt = false

[functions.carousel-engine]
verify_jwt = false

[functions.generate-slide-image]
verify_jwt = false
